--  with sPrint; use sPrint;
--  with PUMP;
--  with PUMP_UNIT;
--
--  package body CASH_REGISTER
--  with SPARK_Mode is
--     ---------
--     -- PAY --
--     ---------
--
--     procedure PAY
--       (cashRegister: in out CASH_REGISTER;
--        AMOUNT: in UNIT.P.FLOAT_NUMBER)
--     is
--     begin
--        print("pay");
--     end PAY;
--
--     --------------
--     -- set pump --
--     --------------
--
--     procedure SET_PUMPED_INFO_TO_CASH_REGISTER
--       (cashRegister: in out CASH_REGISTER)
--     is
--  --        pumpUnit_for_cash_register: PUMP_UNIT_ID;
--  --        topay: UNIT.FLOAT_NUMBER;
--  --        totaltopay: UNIT.FLOAT_NUMBER;
--     begin
--  --        topay:= UNIT.GET_TO_PAY(pumpUnit);
--  --        totaltopay:=cashRegister.TOTAL_PUMP_TO_PAY;
--  --        pumpUnit_for_cash_register.ID :=UNIT.GET_ID(pumpUnit);
--  --        pumpUnit_for_cash_register.TO_PAY := topay;
--  --        pumpUnit_for_cash_register.PUMPED := UNIT.GET_PUMPED(pumpUnit);
--  --        pumpUnit_for_cash_register.FUEL := UNIT.GET_FUEL(pumpUnit);
--  --        cashRegister.UNIT_1 := pumpUnit_for_cash_register;
--  --        totaltopay :=  totaltopay +topay;
--        print("pay");
--     end SET_PUMPED_INFO_TO_CASH_REGISTER;
--
--
--  end CASH_REGISTER;
